export const RelevamientosMock = [
  {
    agente: 'Seed User',
    nombre: 'Juan Pérez',
    email: 'juan.perez@example.com',
    telefono: 1234567890,
    razon: 'Solicitud de instalación de servicio',
    direccion: 'Juan Cornelio Moyano 195',
    latitud: -32.8433517,
    longitud: -68.8320765,
    provincia: 'Mendoza',
    localidad: 'Las Heras',
  },
  {
    agente: 'Seed User',
    nombre: 'María Gómez',
    email: 'maria.gomez@example.com',
    telefono: 9876543210,
    razon: 'Consulta sobre servicio',
    direccion: 'Av. José Vicente Zapata 63',
    latitud: -32.889629,
    longitud: -68.844196,
    provincia: 'Mendoza',
    localidad: 'Mendoza',
  },
];
