export const EquiposMock = [
  {
    nombre: 'HUAWEI',
    agente: 'SeedAdmin',
    equipo: 'Lbe-5ac-gen2',
    macEquipo: '00:11:22:33:44:55',
    isInstalled: false,
    isAvailable: true,
  },
  {
    nombre: 'NOKIA',
    agente: 'SeedAdmin',
    equipo: 'Hzx-5ac-gen2',
    macEquipo: '00:11:22:33:44:22',
    isInstalled: false,
    isAvailable: true,
  },
  {
    nombre: 'SAMSUNG',
    agente: 'SeedAdmin',
    equipo: 'NanoLoco M5',
    macEquipo: '00:11:22:33:44:33',
    isInstalled: true,
    isAvailable: false,
  },
  {
    nombre: 'SAMSUNG',
    agente: 'SeedAdmin',
    equipo: 'NanoLoco M5',
    macEquipo: '00:11:22:33:44:34',
    isInstalled: true,
    isAvailable: false,
  },
  {
    nombre: 'NOKIA',
    agente: 'SeedAdmin',
    equipo: 'Hzx-5ac-gen2',
    macEquipo: '00:11:22:33:44:27',
    isInstalled: true,
    isAvailable: false,
  },
];
